### ISSUE TITLE
install pinto in docker

### ISSUE THREAD

**Issue by JaSei** [thaljef/Pinto#232]
Hi,
we have troubles with install pinto in docker (official docker perl:5.24)...

We have minimal `Dockerfile`:
```
FROM perl:5.24

ENV PINTO_REPOSITORY_ROOT /var/lib/pinto
ENV PINTO_USERNAME pinto

RUN cpanm --notest Term::ReadKey && cpanm -v Pinto
```
I added [log.txt](https://github.com/thaljef/Pinto/files/581127/log.txt) with cpanm install log.

Can you please have a look?

Thank you

**Comment by fgabolde** [comment]
@JaSei Did you ever manage to do this?

I've tried installing Pinto from CPAN and ran into dependency issues, didn't really feel like handling them so went back to using the getpinto installer.

I'm currently stuck because it's trying to install IO::Prompt 0.997002 which requires a TTY to pass its tests (0.997003 fixed this).

**Comment by kiwiroy** [comment]
I've just spotted that it is possible to reproduce @JaSei's report without Docker thus:

`env -u USER -u LOGNAME -u USERNAME -u LOGIN prove -lr t/04-server/01-functional.t`

i.e. [this](https://github.com/thaljef/Pinto/blob/master/t/lib/Pinto/Tester.pm#L36) means that `ENV PINTO_USERNAME pinto` is not enough.

I would suggest that the following should suffice given [this](https://github.com/thaljef/Pinto/blob/master/lib/Pinto/Util.pm#L377).

```Dockerfile
FROM perl:5.24

ENV PINTO_REPOSITORY_ROOT /var/lib/pinto
ENV PINTO_USERNAME pinto
ENV USERNAME pinto

RUN cpanm --quiet Pinto
```

**Comment by JaSei** [comment]
@kiwiroy Work like a charm. Thanks
